variable "aws_region" {
  type    = string
  default = "eu-central-1"
}

variable "instance_type" {
  type    = string
  default = "t2.micro"
}

variable "aws_access_key" {
  type = string
}

variable "aws_secret_key" {
  type = string
}

variable "amis" {
  type = map(any)
  default = {
    "eu-central-1" : "ami-0d527b8c289b4af7f" #Ubuntu 20.04
  }
}

variable "cidr_block" {
  type    = string
  default = "10.0.0.0/16"
}

variable "availability_zones" {
  type    = list(string)
  default = ["eu-central-1a", "eu-central-1b"]
}

variable "db_name" {
  description = "The database name"
  default     = "wordpress"
}

variable "db_admin" {
  description = "The dbadmin username"
  default     = "wordpress"
}

variable "db_password" {
  description = "The dbadmin password"
  default     = "wppassword"
  sensitive   = true
}

variable "workstation_ip" {
  type    = string
  default = "0.0.0.0/0"
}

variable "bastion_instance_type" {
  type    = string
  default = "t2.micro"
}

variable "app_instance_type" {
  type    = string
  default = "t2.micro"
}

variable "db_instance_type" {
  type    = string
  default = "t2.micro"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}